"""Fix columnas duplicadas

Revision ID: 44814530f8bb
Revises: 60b419bc63fd
Create Date: 2025-07-03 09:52:17.510513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44814530f8bb'
down_revision = '60b419bc63fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_final_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cliente_final', ['cliente_final_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_final_id')

    # ### end Alembic commands ###
