"""Fix relación cliente

Revision ID: 60b419bc63fd
Revises: b2639a78fefe
Create Date: 2025-07-03 09:38:45.398232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b419bc63fd'
down_revision = 'b2639a78fefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuentas_finales')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('filtro_netflix')
        batch_op.drop_column('filtro_dispositivo')
        batch_op.drop_column('filtro_actualizar_hogar')

    with op.batch_alter_table('cliente_final', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cuenta_cliente_final_id_fkey'), type_='foreignkey')
        batch_op.drop_column('cliente_final_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_final_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('cuenta_cliente_final_id_fkey'), 'cliente_final', ['cliente_final_id'], ['id'])

    with op.batch_alter_table('cliente_final', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filtro_actualizar_hogar', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filtro_dispositivo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filtro_netflix', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    op.create_table('cuentas_finales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('fecha_compra', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_expiracion', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente_final.id'], name=op.f('cuentas_finales_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cuentas_finales_pkey'))
    )
    # ### end Alembic commands ###
