"""Add pin_final to Cuenta

Revision ID: b2639a78fefe
Revises: 
Create Date: 2025-07-02 17:45:48.470389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2639a78fefe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filtro')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('filtro_netflix')

    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filtro_netflix', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filtro_dispositivo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filtro_actualizar_hogar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filtro_codigo_temporal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cliente_final_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cliente_final', ['cliente_final_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_final_id')
        batch_op.drop_column('filtro_codigo_temporal')
        batch_op.drop_column('filtro_actualizar_hogar')
        batch_op.drop_column('filtro_dispositivo')
        batch_op.drop_column('filtro_netflix')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filtro_netflix', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('filtro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('filtro_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('filtro_pkey'))
    )
    # ### end Alembic commands ###
